### ISSUE TITLE
website of uku.js always shown as “loadig”

### ISSUE THREAD

**Issue by Viggo95** [momoko8443/ukulelejs#26]
![image](https://user-images.githubusercontent.com/22092110/40588164-079f5fe2-620c-11e8-80cb-9428e9a03e41.png)

I've already opened VPN

**Comment by momoko8443** [comment]
Hi Bloom， could you check your network again？Ukulele.js official website is running on the github.io server, it works well for me.

**Comment by Viggo95** [comment]
Well, it works well at the moment.
